In [157]:
import numpy as np

In [158]:
mat1D = np.array([1,2,3,4,5,6,7,8,9])
mat2D = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
mat2D10 = np.array([[10,20,30],[40,50,60],[70,80,90]])

In [159]:
print(f"Matriks 1D :\n {mat1D}")
print(f"Matriks 1D indeks ke 7 : {mat1D[7]}")
print(f"Matriks 1D * 10 : {mat1D * 10}")

Matriks 1D :
 [1 2 3 4 5 6 7 8 9]
Matriks 1D indeks ke 7 : 8
Matriks 1D * 10 : [10 20 30 40 50 60 70 80 90]


In [160]:
print(f"Matriks 2D :\n {mat2D}")
print(f"Matriks 2D * 10 :\n {mat2D * 10}")
print(mat2D10 [0])
print(mat2D10 [0] [2])

Matriks 2D :
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Matriks 2D * 10 :
 [[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]
[10 20 30]
30


In [161]:
print(mat1D.shape)
print(mat2D.shape)

(9,)
(4, 3)


In [162]:
print(f"Ukuran dari mat1D : {mat1D.size}")
print(f"Ukuran dari mat2D : {mat2D.size}")

Ukuran dari mat1D : 9
Ukuran dari mat2D : 12


In [163]:
#Special Matriks
mZero = np.zeros((3,3))
mOne = np.ones((3,3))
mFull = np.full((4,4),7) #Membuat array ukuran 4*4 diisi dengan nilai 7
mIdentity = np.eye((4))
mFRandom1D = np.random.rand(5) 
mFRandom2D = np.random.rand(3,3) 
mIRandom1D = np.random.randint(10,100,size=5)
mIRandom2D = np.random.randint(10,100,size=(4,4))
print(f"Matriks mZero :\n{mZero}")
print(f"Matriks mOne :\n{mOne}")
print(f"Matriks mFull :\n{mFull}")
print(f"Matriks Identitas:\n{mIdentity}")
print(f"Matriks mFRandom1D :\n{mFRandom1D}")
print(f"Matriks mFRandom2D :\n{mFRandom2D}")
print(f"Matriks mIRandom1D :\n{mIRandom1D}")
print(f"Matriks mIRandom2D :\n{mIRandom2D}")

Matriks mZero :
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Matriks mOne :
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Matriks mFull :
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
Matriks Identitas:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Matriks mFRandom1D :
[0.5291997  0.19940898 0.48446738 0.54582975 0.89339243]
Matriks mFRandom2D :
[[0.73162502 0.26621473 0.46421322]
 [0.96529241 0.82234776 0.5706209 ]
 [0.05646046 0.79100731 0.7509304 ]]
Matriks mIRandom1D :
[23 79 24 15 64]
Matriks mIRandom2D :
[[13 42 86 51]
 [64 71 16 13]
 [63 67 78 22]
 [16 43 26 56]]


In [164]:
#Mengubah Bentuk Array
data = np.array([[1,2,3],[4,5,6],[7,8,9]])
mshape = data.reshape((9,1))
mFlat = data.flatten()
print(f"Matriks Data :\n{data}")
print(f"Matriks Reshape :\n{mshape}")
print(f"Matriks mFlat :\n{mFlat}")

Matriks Data :
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matriks Reshape :
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
Matriks mFlat :
[1 2 3 4 5 6 7 8 9]


In [171]:
#Deskriptif Statistik
x = np.array([1,2,3,4])
y = np.array([2,5,7,9])

#Menghitung dot product
r1 = np.dot(x,y)
r2 = np.add(x,y)
print(f"hasil dari dot product:{r1}")
print(f"Hasil Penjummlahan Matriks: {r2}")
print(f"Nilai Minimum : {y.min()}")
print(f"Nilai maksimum : {y.max()}")
print(f"Nilai Rata Rata : {y.mean()}")
print(f"Nilai Total:{y.sum()}")
print(f"Nilai Deviasi: {y.std()}")

hasil dari dot product:69
Hasil Penjummlahan Matriks: [ 3  7 10 13]
Nilai Minimum : 2
Nilai maksimum : 9
Nilai Rata Rata : 5.75
Nilai Total:23
Nilai Deviasi: 2.5860201081971503


In [181]:
#Filtering

nilaiPemrograman = np.array([100,90,100,80,50,50,50,40])
#Tampilkan nilai Pemrograman yang lebih dari 50 -> lulus
#Berapakah Mahasiswa yang lulus
jmlLulus = nilaiPemrograman [nilaiPemrograman >50]
print(jmlLulus)
print(f"Mahasiswa yang lulus Sebanyak: {jmlLulus.size}")
print(f"Mahasiswa yang tidak Lulus : {nilaiPemrograman.size -jmlLulus.size}")

[100  90 100  80]
Mahasiswa yang lulus Sebanyak: 4
Mahasiswa yang tidak Lulus : 4


<b>PROJECT GENERATE DATA</b><br>

Buatlah 100 data Customer CC, yang akan digunakan untuk prediksi atau klasisfikasi yaitu:
<ol> 
    <li>Usia : 17 - 60 </li>
    <li>Gender : L/P </li>
    <li>Transksi Perbulan : 0 - 50</li>
    <li>Pembayaran : Buruk,Sedang,Bagus</li>
<ol>

In [211]:
import numpy as np
import pandas as pd
jmlhData = 100
usia = np.random.randint(17,61,size=jmlhData)
Gender = np.random.choice(['L','P'],size=jmlhData)
transaksi = np.random.randint(0,51,size=jmlhData)
pembayaran = np.random.choice(['Buruk','sedang','Bagus'],size=jmlhData)

df = pd.DataFrame ({
    'usia' : usia,
    'Gender' : Gender,
    'transaksi' : transaksi,
    'pembayaran' : pembayaran
})
print(df)
print(df.info()) #Menampilkn karakteristik data
print(df.head())#Menampilkan isi tabel 5 baris pertama

#Tampilkan Usia Paling Muda
print(f"Usia Paling Muda : {df['usia'].min()}")
print(f"Usia Paling Tua : {df['usia'].max()}")

#Menampilkan JUmlah CS Laki LAki 
jmlL = df[df['Gender']=='L']
print(f"Jumlah CS laki - Laki : {jmlL.size/4}")
print(f"Jumlah CS Perempuan : {jmlL['Gender'].size}")
df.to_csv("Data CC Customer.csv")



    usia Gender  transaksi pembayaran
0     36      P         49     sedang
1     47      P          7     sedang
2     42      P         19      Buruk
3     26      L          3      Bagus
4     27      L         49      Buruk
..   ...    ...        ...        ...
95    20      L         16      Buruk
96    51      P         40      Buruk
97    46      P          0      Buruk
98    52      P          5      Bagus
99    50      P         32     sedang

[100 rows x 4 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   usia        100 non-null    int32 
 1   Gender      100 non-null    object
 2   transaksi   100 non-null    int32 
 3   pembayaran  100 non-null    object
dtypes: int32(2), object(2)
memory usage: 2.5+ KB
None
   usia Gender  transaksi pembayaran
0    36      P         49     sedang
1    47      P          7     sedang
2    42    